version: '2'
services:
  ftp:
    build: .
    command: bash upload-csv.sh
    container_name: ftp
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/folder_on_disk/data:/home/ftpusers/"
      - "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
      - '.:/ftp'
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "test"
      FTP_USER_PASS: "test"
      FTP_USER_HOME: "/home/test"
    restart: always
#     networks:
#       - app1_default # external network (app1)

# networks:
#   app1_default: # external network (app1)
#     external: true